-- =============================================================================
-- Snowflake setup for dbt (netflix project)
-- Run as ACCOUNTADMIN in Snowflake Worksheets. Execute the whole script.
-- =============================================================================

-- 0. Create warehouse first (required before creating database)
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- 1. Create role and dbt user
CREATE ROLE IF NOT EXISTS TRANSFORM;

CREATE USER IF NOT EXISTS dbt
  PASSWORD = 'dbtPassword123'
  LOGIN_NAME = 'dbt'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_WAREHOUSE = 'COMPUTE_WH'
  DEFAULT_ROLE = 'TRANSFORM'
  DEFAULT_NAMESPACE = 'NETFLIX_MOVIE.RAW'
  COMMENT = 'DBT user used for data transformation';

ALTER USER dbt SET TYPE = LEGACY_SERVICE;
GRANT ROLE TRANSFORM TO USER dbt;

-- 2. Create database and schema (use warehouse so we have a session)
USE WAREHOUSE COMPUTE_WH;
CREATE DATABASE IF NOT EXISTS NETFLIX_MOVIE;
USE DATABASE NETFLIX_MOVIE;
CREATE SCHEMA IF NOT EXISTS RAW;

-- 3. Grant TRANSFORM role what it needs to run dbt
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT USAGE ON DATABASE NETFLIX_MOVIE TO ROLE TRANSFORM;
GRANT USAGE ON SCHEMA NETFLIX_MOVIE.PUBLIC TO ROLE TRANSFORM;
GRANT USAGE ON SCHEMA NETFLIX_MOVIE.RAW TO ROLE TRANSFORM;
GRANT CREATE SCHEMA ON DATABASE NETFLIX_MOVIE TO ROLE TRANSFORM;
GRANT CREATE TABLE ON SCHEMA NETFLIX_MOVIE.RAW TO ROLE TRANSFORM;
GRANT CREATE VIEW ON SCHEMA NETFLIX_MOVIE.RAW TO ROLE TRANSFORM;
GRANT CREATE STAGE ON SCHEMA NETFLIX_MOVIE.RAW TO ROLE TRANSFORM;
GRANT CREATE FILE FORMAT ON SCHEMA NETFLIX_MOVIE.RAW TO ROLE TRANSFORM;

-- 4. Verify (run as ACCOUNTADMIN; should return rows)
-- SHOW SCHEMAS IN DATABASE NETFLIX_MOVIE;

-- Optional: if dbt will write to other schemas (e.g. ANALYTICS, MART)
-- CREATE SCHEMA IF NOT EXISTS NETFLIX_MOVIE.ANALYTICS;
-- GRANT USAGE ON SCHEMA NETFLIX_MOVIE.ANALYTICS TO ROLE TRANSFORM;
-- GRANT CREATE TABLE ON SCHEMA NETFLIX_MOVIE.ANALYTICS TO ROLE TRANSFORM;
-- GRANT CREATE VIEW ON SCHEMA NETFLIX_MOVIE.ANALYTICS TO ROLE TRANSFORM;
